config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cats#index"
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :cat_params, only: [:create]
    before_action :set_cat, only: [:show]

    def index
        @cats = Cat.all
    end

    def new 
        @cat = Cat.new
    end
    
    def create
        current_user.cats.create(cat_params) #this wont work until devise done
        redirect_to cats_path
    end

    def destroy
        @cat = Cat.find(params[:id])
        if @cat.present?
          @cat.destroy
        end
        redirect_to root_url
    end
    
private

    def cat_params
        params.require(:cat).permit(:name, :breed, :age, :sex, :price, :description, :picture)
    end

    def set_cat
        @cat = Cat.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_with(model: @cat, class: "new-cat-form") do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :breed %>:
  <%= f.text_field :breed %>
  <br>
  <br>
  <%= f.label :age %>:
  <%= f.number_field :age %>
  <br>
  <br>
  <%= f.label :sex %>:
  <%= f.text_field :sex %>
  <br>
  <br>
  <%= f.label :price %>:
  <%= f.text_field :price %>
  <br>
  <br>
  <%= f.label :description %>:
  <%= f.text_area :description, size: "20x6" %>
  <br>
  <br>
  <br>
  <br>
  <%= f.label :picture %>
  <%= f.file_field :picture, accept: ['image/png', 'image/jpg', 'image/jpeg'] %>
  <br>
  <br>
  <%= f.submit "Create" %>

<% end %>

app/views/cats/index.html.erb
<h2>Cats</h2>
<%= link_to "Add a new cat", new_cat_path %>

<% @cats.each do |cat| %>
  <div>
    <h3>Name: <%= cat.name %></h3>
    <h3>Breed: <%= cat.breed %></h3>
    <h3>Age: <%= cat.age %></h3>
    <h3>Sex: <%= cat.sex %></h3>
    <h3>Price: <%= cat.price %></h3>
    <h3>Description: <%= cat.description %></h3>
    <h4>Created by <%= cat.user.email %></h4>
    <%= link_to "Show", cat_path(cat.id)  %>
    <% if user_signed_in? && current_user.cats.include?(cat) %>
      <%= link_to "Delete", cat_path(cat.id), method: :delete %>
    <% end %>
  </div>
<% end %>

<h2>Email Us</h2>
<p>
Email us at <br>
<b>info@catadoptionagency.com.au</b> or fill in the form below
</p>

<h2>Call Us</h2>
<p>

Within Australia Tel :(02) 9600 0000 <br>
International Tel: +61 2 9600 0000 <br><br>

<b>Business Hours</b><br>
Monday - Friday 9:00am - 5:00pm <br>
Saturday 9:00am - 3:00pm <br><br>

Sunday CLOSED
</p>

<h2>Talk to us in person</h2>
Level 2/7 Kelly St, Ultimo, Australia <br><br>

<b>Please make an appointment</b> just incase the pet you're interestd in is adopted. <br><br>


<div class="container">
  <form action="action_page.php">

    <label for="fname">First Name</label>
    <br>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">
    <br>
    <label for="lname">Last Name</label>
    <br>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">
    <br>
    <label for="subject">Subject</label>
    <br>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
    <br>

    <input type="submit" value="Submit">

  </form>

</div>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/show.html.erb
<div class="container p-3 my-3 border">
  <h3>Name: <%= @cat.name %></h3>
  <h3>Breed: <%= @cat.breed %></h3>
  <h3>Age: <%= @cat.age %></h3>
  <h3>Price: $<%= @cat.price %>.00</h3>
  <h3>Description: <%= @cat.description %></h3>
</div>
<button type="button" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">
<%= link_to "Back", cats_path %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatAdoption2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap',media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <nav class="navbar navbar-light">
      <% if user_signed_in? %>
        <span>Hello <%= current_user.email %></span>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_user_session_path  %>
        <%= link_to "Sign up", new_user_registration_path  %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>